export const SEARCH = "SEARCH_MOVIE";
export const ADD = "ADD_FAVORITE_FILM";
export const REMOVE = "REMOVE_MOVIE_FROM_FAVORITE_LIST";
export const REGISTER = "REGISTER_FAVORITES";
export const GET_MOVIE = "GET_MOVIE_INFO_INTO_STATE";
export const GET_LIST = "GET_LIST_INTO_STATE";